#!/usr/bin/env bash

cd $T2_HOME

source "scripts/aux/script_requires_framework_as_param"

read -p "Enter JIRA ticket number:" PROJECT_NAME

# if no ticket -> exit process 
if [ "$PROJECT_NAME" ]; then
    echo "Creating $PROJECT_NAME..."
else
    echo "No ticket provided"
    exit 1
fi

# to lowercase
PROJECT_NAME=$(echo "t2-$PROJECT_NAME" | tr '[:upper:]' '[:lower:]')

CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/cached-$FRAMEWORK"
PROJECT_DIR_PATH="$T2_HOME/projects/$PROJECT_NAME"

# copy project from cache into t2/projects folder
cp -r $CACHED_PROJECT_DIR_PATH/. $PROJECT_DIR_PATH

# update ag-grid.config file
gsed -i "s/TICKET=.*/TICKET=\"$PROJECT_NAME\"/" $PROJECT_DIR_PATH/ag-grid.config.sh

# install project dependencies
npm i --prefix $PROJECT_DIR_PATH

# open in vscode 
code $PROJECT_DIR_PATH

# update cache in background
source "scripts/t2-update-cache" $FRAMEWORK > /dev/null 2>&1 & 
