#!/usr/bin/env bash

cd $T2_HOME

source "scripts/helpers/script_requires_framework_as_param"

if [ -z $2 ] ; then
  echo 'you must pass the project name as the second paramater to this script'
  echo 'e.g. t2-get [framework] [project_name]'
  exit 1
fi

# to lowercase
PROJECT_NAME=$(echo "$2" | tr '[:upper:]' '[:lower:]')

echo "Creating [$PROJECT_NAME] $FRAMEWORK project..."

CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/cached-$FRAMEWORK"
NEW_PROJECT_DIR_PATH="$T2_HOME/projects/$PROJECT_NAME"

# copy project contents from t2/cache into t2/projects folder
# cp -r $CACHED_PROJECT_DIR_PATH/. $NEW_PROJECT_DIR_PATH

# move project contents from t2/cache into t2/projects folder
mkdir $NEW_PROJECT_DIR_PATH
mv $CACHED_PROJECT_DIR_PATH/* $NEW_PROJECT_DIR_PATH/

# update ag-grid.config file
gsed -i "s/TICKET=.*/TICKET=\"$PROJECT_NAME\"/" $NEW_PROJECT_DIR_PATH/ag-grid.config.sh

# install project dependencies
# echo "installing dependencies..."
# npm i --prefix $NEW_PROJECT_DIR_PATH

# https://fsymbols.com/generators/carty/

echo "───────────────────────────▓▓▓▓▓▓▓────────────▒▒▒▒▒▒"
echo "─────────────────────────▓▓▒▒▒▒▒▒▒▓▓────────▒▒░░░░░░▒▒"
echo "───────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▓▓────▒▒░░░░░░░░░▒▒▒"
echo "──────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒░░░░░░░░░░░░░░▒"
echo "─────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░▒"
echo "─────────────────────▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░▒"
echo "────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░▒"
echo "───────────────────▓▓▒▒▒▒▒▒░░░░░░░░░░░▒▒░░▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒"
echo "───────────────────▓▓▒▒▒▒▒▒▀▀▀▀▀███▄▄▒▒▒░░░▄▄▄██▀▀▀▀▀░░░░░░▒"
echo "───────────────────▓▓▒▒▒▒▒▒▒▄▀████▀███▄▒░▄████▀████▄░░░░░░░▒"
echo "───────────────────▓▓▒▒▒▒▒▒█──▀█████▀─▌▒░▐──▀█████▀─█░░░░░░▒"
echo "───────────────────▓▓▒▒▒▒▒▒▒▀▄▄▄▄▄▄▄▄▀▒▒░░▀▄▄▄▄▄▄▄▄▀░░░░░░░▒"
echo "────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░▒"
echo "─────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░▒"
echo "──────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀▀▀░░░░░░░░░░░░░░▒"
echo "───────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░▒▒"
echo "────────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▄▄▄▄▄▄▄▄▄░░░░░░░░▒▒"
echo "─────────────────────────▓▓▒▒▒▒▒▒▒▄▀▀▀▀▀▀▀▀▀▀▀▄░░░░░▒▒"
echo "──────────────────────────▓▓▒▒▒▒▒▀▒▒▒▒▒▒░░░░░░░▀░░░▒▒"
echo "───────────────────────────▓▓▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒"
echo "─────────────────────────────▓▓▒▒▒▒▒▒▒▒▒░░░░░░░░▒▒"
echo "──────────────────────────────▓▓▒▒▒▒▒▒▒▒░░░░░░░▒▒"
echo "────────────────────────────────▓▓▒▒▒▒▒▒░░░░░▒▒"
echo "──────────────────────────────────▓▓▒▒▒▒░░░░▒▒"
echo "───────────────────────────────────▓▓▒▒▒░░░▒▒"
echo "─────────────────────────────────────▓▓▒░▒▒"
echo "──────────────────────────────────────▓▒░▒"
echo "───────────────────────────────────────▓▒"
echo "██╗████████╗██╗░██████╗  ░██████╗░██████╗░██╗██████╗░  ████████╗██╗███╗░░░███╗███████╗"
echo "██║╚══██╔══╝╚█║██╔════╝  ██╔════╝░██╔══██╗██║██╔══██╗  ╚══██╔══╝██║████╗░████║██╔════╝"
echo "██║░░░██║░░░░╚╝╚█████╗░  ██║░░██╗░██████╔╝██║██║░░██║  ░░░██║░░░██║██╔████╔██║█████╗░░"
echo "██║░░░██║░░░░░░░╚═══██╗  ██║░░╚██╗██╔══██╗██║██║░░██║  ░░░██║░░░██║██║╚██╔╝██║██╔══╝░░"
echo "██║░░░██║░░░░░░██████╔╝  ╚██████╔╝██║░░██║██║██████╔╝  ░░░██║░░░██║██║░╚═╝░██║███████╗"
echo "╚═╝░░░╚═╝░░░░░░╚═════╝░  ░╚═════╝░╚═╝░░╚═╝╚═╝╚═════╝░  ░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚══════╝"
echo "──────────────────$NEW_PROJECT_DIR_PATH"

if [ -n $MY_EDITOR ]; then
    # open in text editor
    $MY_EDITOR $NEW_PROJECT_DIR_PATH  
fi

# update cache in foreground
source "scripts/t2-update-cache" $FRAMEWORK
# update cache in background
# source "scripts/t2-update-cache" $FRAMEWORK > /dev/null 2>&1 & 
