#!/usr/bin/env bash 

if [ $# -eq 0 ]
  then
    COMMIT_MESSAGE='update'
  else 
    COMMIT_MESSAGE=$1
fi

T2_PROJECTS_DIR_PATH="$T2_HOME/projects"

# if running script from outside of our projects folder -> exit
if [[ $PWD != $T2_PROJECTS_DIR_PATH/** ]]
then
    echo "You must run this script from within a subdirectory inside $T2_PROJECTS"
    exit 1
fi

# if ag-grid.config.sh file missing -> exit
if [[ -f ag-grid.config.sh ]]
then
    echo 'reading ag-grid.config.sh file...'
else 
    echo "ag-grid.config.sh file is missing"
    exit 1
fi

source "./ag-grid.config.sh"

cd $T2_HOME

git add . && /
git commit -m "$COMMIT_MESSAGE" && /
git push && /

echo "complete"
echo "======================================================"
echo "LINK TO CODESANDBOX: https://codesandbox.io/s/github/ahmedagadir/t2/tree/main/projects/${TICKET}"
# stackblitz isnt really working 
# echo "LINK TO STACKBLITZ: https://stackblitz.com/github/ahmedagadir/t2/tree/main/projects/${TICKET}"
echo "======================================================"

# open https://codesandbox.io/s/github/ahmedagadir/t2/tree/main/projects/${TICKET}