#!/usr/bin/env bash

if [ $# -eq 0 ] ; then
  echo 'you must pass a framework as a parameter to this script'
  exit 1
fi

# to lowercase
FRAMEWORK=$(echo "$1" | tr '[:upper:]' '[:lower:]')

if [ ! $FRAMEWORK == 'angular' ] && [ ! $FRAMEWORK == 'react' ] && [ ! $FRAMEWORK == 'vue' ] && [ ! $FRAMEWORK == 'vanilla' ] ; then
  echo 'you must pass one of these parameters to this script: angular, react, vue, vanilla'
  exit 1
fi